var Users = [
{
  "login": "dwyanalford",
  "id": 24403219,
  "avatar_url": "https://avatars2.githubusercontent.com/u/24403219?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/dwyanalford",
  "html_url": "https://github.com/dwyanalford",
  "followers_url": "https://api.github.com/users/dwyanalford/followers",
  "following_url": "https://api.github.com/users/dwyanalford/following{/other_user}",
  "gists_url": "https://api.github.com/users/dwyanalford/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/dwyanalford/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/dwyanalford/subscriptions",
  "organizations_url": "https://api.github.com/users/dwyanalford/orgs",
  "repos_url": "https://api.github.com/users/dwyanalford/repos",
  "events_url": "https://api.github.com/users/dwyanalford/events{/privacy}",
  "received_events_url": "https://api.github.com/users/dwyanalford/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Dwyan Alford",
  "company": "Brooklyn View Enterprises",
  "blog": "www.waxandoils.com",
  "location": "Sterling, VA",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 19,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2016-12-06T04:31:01Z",
  "updated_at": "2017-02-18T15:33:21Z"
},
{
  "login": "EtWham",
  "id": 24592304,
  "avatar_url": "https://avatars1.githubusercontent.com/u/24592304?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/EtWham",
  "html_url": "https://github.com/EtWham",
  "followers_url": "https://api.github.com/users/EtWham/followers",
  "following_url": "https://api.github.com/users/EtWham/following{/other_user}",
  "gists_url": "https://api.github.com/users/EtWham/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/EtWham/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/EtWham/subscriptions",
  "organizations_url": "https://api.github.com/users/EtWham/orgs",
  "repos_url": "https://api.github.com/users/EtWham/repos",
  "events_url": "https://api.github.com/users/EtWham/events{/privacy}",
  "received_events_url": "https://api.github.com/users/EtWham/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 18,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2016-12-15T17:04:46Z",
  "updated_at": "2017-05-20T01:11:54Z"
  }
];

module.exports = Users;


